# Generated by Django 3.2 on 2022-12-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adressen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('strasse', models.CharField(max_length=100)),
                ('hausnummer', models.IntegerField()),
                ('plz', models.IntegerField()),
                ('ort', models.CharField(max_length=100)),
                ('image', models.ImageField(max_length=255, upload_to='images/')),
            ],
        ),
    ]
